/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sirs.remotedocs;

/**
 *
 * @author tomaz
 */
public class CustomDialog extends javax.swing.JFrame {

    private int permission;
    /**
     * Creates new form CustomDialog
     */
    public CustomDialog(int perm) {
        initComponents();
        jDialog1.setVisible(true);
        this.permission = perm;
        if(permission == 0){
            editor_rb.setSelected(true);
        }   
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        editor_rb = new javax.swing.JRadioButton();
        viewer_rb = new javax.swing.JRadioButton();
        permissions_buttonGroup = new javax.swing.ButtonGroup();

        permissions_buttonGroup.add(editor_rb);
        editor_rb.setText("Editor");
        editor_rb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editor_rbMouseClicked(evt);
            }
        });

        permissions_buttonGroup.add(viewer_rb);
        viewer_rb.setText("Viewer");
        viewer_rb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewer_rbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(editor_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(viewer_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editor_rb)
                    .addComponent(viewer_rb))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewer_rbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewer_rbMouseClicked
        this.permission = 1;
    }//GEN-LAST:event_viewer_rbMouseClicked

    private void editor_rbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editor_rbMouseClicked
        this.permission = 0;
    }//GEN-LAST:event_editor_rbMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton editor_rb;
    private javax.swing.JDialog jDialog1;
    private javax.swing.ButtonGroup permissions_buttonGroup;
    private javax.swing.JRadioButton viewer_rb;
    // End of variables declaration//GEN-END:variables
}
