/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sirs.remotedocs;

import sirs.remotedocs.grpc.Contract.*;
import io.grpc.StatusRuntimeException;
import javax.swing.JOptionPane;

/**
 *
 * @author tomaz
 */
public class LoginRegisterForm extends javax.swing.JFrame {
    
    private ClientApp clientApp;
    /**
     * Creates new form LoginRegisterForm
     * @param formSelector
     * @param option
     */
    public LoginRegisterForm(ClientApp formSelector, String option) {
        initComponents();
        LoginRegister_btn.setText(option); 
        back_btn.requestFocusInWindow();
        this.clientApp = formSelector;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginRegister_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        username_layeredPane = new javax.swing.JLayeredPane();
        username_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        username_label = new javax.swing.JLabel();
        password_layeredPane = new javax.swing.JLayeredPane();
        password_tf = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        LoginRegister_btn.setBackground(new java.awt.Color(255, 255, 204));
        LoginRegister_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginRegister_btn.setText("LOGIN");
        LoginRegister_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginRegister_btnMouseClicked(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(255, 255, 204));
        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back_btn.setText("BACK");
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Alien Encounters", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REMOTE DOCS");

        username_tf.setBackground(new java.awt.Color(255, 102, 51));
        username_tf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username_tf.setForeground(new java.awt.Color(255, 255, 255));
        username_tf.setBorder(null);
        username_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_tfFocusLost(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pessoa-do-sexo-masculino-24.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        username_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username_label.setForeground(new java.awt.Color(255, 255, 255));
        username_label.setText("Username");

        username_layeredPane.setLayer(username_tf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        username_layeredPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        username_layeredPane.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        username_layeredPane.setLayer(username_label, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout username_layeredPaneLayout = new javax.swing.GroupLayout(username_layeredPane);
        username_layeredPane.setLayout(username_layeredPaneLayout);
        username_layeredPaneLayout.setHorizontalGroup(
            username_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(username_layeredPaneLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(username_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(username_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(username_layeredPaneLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        username_layeredPaneLayout.setVerticalGroup(
            username_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, username_layeredPaneLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(username_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(username_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(username_layeredPaneLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        password_tf.setBackground(new java.awt.Color(255, 102, 51));
        password_tf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        password_tf.setForeground(new java.awt.Color(255, 255, 255));
        password_tf.setBorder(null);
        password_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_tfFocusLost(evt);
            }
        });
        password_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_tfActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-desbloquear-24.png"))); // NOI18N

        password_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        password_label.setForeground(new java.awt.Color(255, 255, 255));
        password_label.setText("password");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        password_layeredPane.setLayer(password_tf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        password_layeredPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        password_layeredPane.setLayer(password_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        password_layeredPane.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout password_layeredPaneLayout = new javax.swing.GroupLayout(password_layeredPane);
        password_layeredPane.setLayout(password_layeredPaneLayout);
        password_layeredPaneLayout.setHorizontalGroup(
            password_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(password_layeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(password_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(password_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(password_layeredPaneLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );
        password_layeredPaneLayout.setVerticalGroup(
            password_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(password_layeredPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(password_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(password_layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(password_layeredPaneLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(username_layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoginRegister_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(username_layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginRegister_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        clientApp.switchForm(this, clientApp.getMenu());
    }//GEN-LAST:event_back_btnMouseClicked

    private void password_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_tfFocusGained
        password_tf.setText("");
    }//GEN-LAST:event_password_tfFocusGained

    private void username_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_tfFocusGained
        if (username_tf.getText().equals("Username")) {
            username_tf.setText("");
        }   
    }//GEN-LAST:event_username_tfFocusGained

    private void password_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_tfFocusLost

    }//GEN-LAST:event_password_tfFocusLost

    private void username_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_tfFocusLost
        if (username_tf.getText().isEmpty()) {
            username_tf.setText("Username");
        }
    }//GEN-LAST:event_username_tfFocusLost

    private void password_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_tfActionPerformed

    private void LoginRegister_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginRegister_btnMouseClicked
        String password = new String(password_tf.getPassword());
        String username = username_tf.getText();
        if(LoginRegister_btn.getText().equals("LOGIN")){
            LoginRequest loginRequest = LoginRequest.newBuilder().setUsername(username).setPassword(password).build();
		    try {
			    LoginResponse loginResponse = clientApp.getFrontend().login(loginRequest);
                password_tf.setText("");
                username_tf.setText("Username");
                clientApp.switchForm(this, clientApp.getDoclist());
                
            }
		    catch (StatusRuntimeException e) {
			    System.out.println("Caught exception with description: " +
			    e.getStatus().getDescription());
                JOptionPane.showMessageDialog(null, e.getStatus().getDescription());
		    }
        }
        else{
            RegisterRequest registerRequest = RegisterRequest.newBuilder().setUsername(username).setPassword(password).build();
		    try {
			    RegisterResponse registerResponse = clientApp.getFrontend().register(registerRequest);
                password_tf.setText("");
                username_tf.setText("Username");
                clientApp.switchForm(this, clientApp.getDoclist());
                
            }
		    catch (StatusRuntimeException e) {
			    System.out.println("Caught exception with description: " +
			    e.getStatus().getDescription());
                JOptionPane.showMessageDialog(null, e.getStatus().getDescription());
		    }
        }     
    }//GEN-LAST:event_LoginRegister_btnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginRegister_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel password_label;
    private javax.swing.JLayeredPane password_layeredPane;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JLabel username_label;
    private javax.swing.JLayeredPane username_layeredPane;
    private javax.swing.JTextField username_tf;
    // End of variables declaration//GEN-END:variables
}
